apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexslice-scheduler
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/0patrichor0/NexSlice.git
    targetRevision: main
    path: gitops/scheduler

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
